import { useState, useEffect } from 'react';
import { useAuth } from '../../context/AuthContext';
import { getCertificateStatus } from '../../services/api';
import { FiDownload, FiAward, FiLock } from 'react-icons/fi';

export default function StudentCertificate() {
  const { user } = useAuth();
  const [eligible, setEligible] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const checkEligibility = async () => {
      try {
        const res = await getCertificateStatus();
        setEligible(res.data.eligible);
      } catch (err) {
        console.error('Failed to check eligibility:', err);
      } finally {
        setLoading(false);
      }
    };
    checkEligibility();
  }, []);

  const handleDownload = () => {
    // Generate a simple clearance certificate
    const certContent = `
      UNIVERSITY CLEARANCE CERTIFICATE
      ================================

      This is to certify that

      Name: ${user.name}
      Student ID: ${user.studentId}
      Email: ${user.email}

      has been cleared by all departments and
      has no pending obligations with the university.

      Date of Issue: ${new Date().toLocaleDateString()}

      This certificate is digitally generated by the
      University Clearance & Exit Management System.
    `;

    const blob = new Blob([certContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `clearance_certificate_${user.studentId}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (loading) return <div className="loading">Loading...</div>;

  return (
    <div className="dashboard">
      <div className="page-header">
        <h1>Clearance Certificate</h1>
        <p>Download your clearance certificate once all departments have approved</p>
      </div>

      {eligible ? (
        <div className="certificate-card eligible">
          <FiAward size={64} className="certificate-icon" />
          <h2>Congratulations!</h2>
          <p>You have been cleared by all departments. You may download your clearance certificate below.</p>
          <button className="btn btn-primary btn-lg" onClick={handleDownload}>
            <FiDownload /> Download Certificate
          </button>
        </div>
      ) : (
        <div className="certificate-card not-eligible">
          <FiLock size={64} className="certificate-icon locked" />
          <h2>Certificate Not Available</h2>
          <p>Your clearance is not yet complete. All departments must approve your clearance before you can download the certificate.</p>
          <p className="hint">Please check your clearance status and ensure all departments have approved your request.</p>
        </div>
      )}
    </div>
  );
}
